// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

import java.util.Set;

import project.AreaType;
import simbad.sim.Boundary;

/************************************************************/
/**
 * 
 */
public class Area {
	/**
	 * 
	 */
	private Set<Boundary> boundaries;
	private AreaType type;
	
	public Area(AreaType type) {
		this.type = type;
	}

	/**
	 * 
	 * @param areaType 
	 */
	public AreaType getAreaType() {
		return type; //Fix this
	}

	/**
	 * 
	 * @return 
	 */
	public Set<Boundary> getBoundaries() {

		return this.boundaries;
	}

	/**
	 * 
	 * @param boundaries 
	 */
	public void setBoundaries(Set<Boundary> boundaries) {
		this.boundaries = boundaries;
	}
};
