// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

import project.AreaType;
import project.Boundaries;

/************************************************************/
/**
 * 
 */
public abstract class Area {
	/**
	 * 
	 */
	private Boundaries boundaries;
	private AreaType type;
	
	public Area(AreaType type) {
		this.type = type;
	}

	/**
	 * 
	 * @param areaType 
	 */
	public AreaType getAreaType() {
		return type; //Fix this
	}

	/**
	 * 
	 * @return 
	 */
	public Boundaries getBoundaries() {

		return this.boundaries;
	}

	/**
	 * 
	 * @param boundaries 
	 */
	public void setBoundaries(Boundaries boundaries) {
		this.boundaries = boundaries;
	}
};
