// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

import java.util.HashSet;
import java.util.Set;

import area.Area;
import project.Rover;

/************************************************************/
/**
 * 
 */
public class Environment {

	/**
	 * 
	 */
	protected Set<Boundary> boundaries;
	private Set<Area> areas;
	public Rover[] rovers;
	
	public Environment(Set<Boundary> b, Set<Area> a, Rover[] r) {
		this.rovers=r;
		this.areas=a;
		this.boundaries=b;
	}

	/**
	 * 
	 * @param boundaries 
	 */
	public void setBoundaries(Set<Boundary> boundaries) {
		this.boundaries=boundaries;
	}

	/**
	 * 
	 *
	 */
	public Set<Boundary> getBoundaries() {
		return boundaries;
	}
	
	public Set<Area> getAreas(){
		return areas;
	}
	
	public void addArea(Area a) {
		areas.add(a);
	}
};
