// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

import project.Area;
import project.Boundaries;
import project.Rover;

/************************************************************/
/**
 * 
 */
public class Environment {
	/**
	 * 
	 */
	private Boundaries boundaries;
	/**
	 * 
	 */
	public Area area;
	/**
	 * 
	 */
	public Rover[] roversInEnvironment;

	/**
	 * 
	 * @param boundaries 
	 */
	public void setBoundaries(Boundaries boundaries) {
	}

	/**
	 * 
	 * @param boundaries 
	 */
	public void getBoundaries(Boundaries boundaries) {
	}
};
