// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

import project.Area;

/************************************************************/
/**
 * 
 */
public class LogicalArea extends Area {

	public LogicalArea(AreaType type) {
		super(type);
		// TODO Auto-generated constructor stub
	}
};
