// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

import project.Area;

/************************************************************/
/**
 * 
 */
public class LogicalArea extends Area {
};
