// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

import java.util.Arrays;

import project.Position;
import project.StrategyType;

/************************************************************/
/**
 * 
 */
class Mission implements RoverObserver{
	/**
	 * 
	 */
	public Mission(Rover r, Position[] positions, AbstractStrategy strat) {
		this.setMission(positions);
		this.rover = r;
		nextPositionIndex = 0;
		nextPosition = missionPoints[nextPositionIndex];
		strategy = strat;
		r.observe(this);
		nextPosition = rover.getPosition();
	}

	private Position nextPosition;
	//public StrategyType[] strategyType;
	//private AbstractStrategy strategy = AbstractStrategy.getInstance();
	private Position[] missionPoints;
	private Position[] unvisitedPoints;
	private Rover rover;
	private int nextPositionIndex;
	private boolean missionStatus;
	private AbstractStrategy strategy;

	/**
	 * 
	 * @param points 
	 */
	public void setMission(Position[] position) {
		missionPoints = position;
		unvisitedPoints = position;
	}

	/**
	 * 
	 */
	public void stopMission() {
	}
		
	public void updateRoverPosition(Position newPos) {
		//System.out.println(rover.getPosition().toString());
		//System.out.println(nextPosition.getX() == newPos.getX() && (nextPosition.getZ() == newPos.getZ()));
		//if(rover.isAtPosition(newPosition)) {
		if((((nextPosition.getX() + 0.1 >= newPos.getX() && nextPosition.getX() - 0.1 <= newPos.getX()) 
				&& (nextPosition.getZ() + 0.1 >= newPos.getZ() && nextPosition.getZ() - 0.1 <= newPos.getZ())) 
				&& !missionStatus) || nextPosition == null) {
			if(unvisitedPoints.length == 0) {
				missionStatus = true;
			} else {
				//nextPositionIndex++;
				nextPosition = strategy.calculateNextPoint(unvisitedPoints, rover.inEnvironment, nextPositionIndex, nextPosition);
				rover.moveToPoint(nextPosition);
				Position tempArray[] = new Position[0];
				if(unvisitedPoints.length-1>0) {
					tempArray = new Position[unvisitedPoints.length-1];
				}
				
				//Should probably be changed to some utility package or moved to some 
				//helper class we make code in as we need it. Basically just ArrayUtils.RemoveElement
				int y = 0;
				for(int x = 0; x < unvisitedPoints.length; x++) {
					if(unvisitedPoints[x].equals(nextPosition)) {
						System.out.println("removed visited point at index " + x);
						x++;
					}
					if(y < unvisitedPoints.length-1) {
						tempArray[y] = unvisitedPoints[x];
					}
					y++;
				}
				unvisitedPoints = tempArray;
			}
		}
	}
	
	public Position getNextPosition() {
		return nextPosition;
	}
	public Position[] getMissionPoints() {
		return missionPoints;
	}
	public Position[] getUnvisitedPoints() {
		return unvisitedPoints;
	}
	
	public boolean getMissionStatus() {
		return missionStatus;
	}
};
