// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MDSD;

import MDSD.Area;

/************************************************************/
/**
 * 
 */
public class PhysicalArea extends Area {
};
