// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MDSD;

/************************************************************/
/**
 * 
 */
public class Point {
	/**
	 * 
	 */
	private int x;
	/**
	 * 
	 */
	private int y;

	/**
	 * 
	 * @param x 
	 * @param y 
	 */
	public void updatePosition(int x, int y) {
	}
};
