// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

/************************************************************/
/**
 * 
 */
public class Position extends Point{

	/**
	 * 
	 */
	private int x;
	/**
	 * 
	 */
	private int y;
	
	public Position(double x, double z) {
		super(x, z);
		// TODO Auto-generated constructor stub
	}

	/**
	 * 
	 * @param x 
	 * @param y 
	 */
	public void updatePosition(int x, int y) {
	}
};
