// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

/************************************************************/
/**
 * 
 */
public class Position extends Point{



	/**
	 * 
	 */
	/**
	 * 
	 */
	
	public Position(double x, double z) {
		super(x, z);
		// TODO Auto-generated constructor stub
	}

	/**
	 * 
	 * @param x 
	 * @param y 
	 */
	public void updatePosition(double x, double z) {
		this.setX(x);
		this.setZ(z);
		
	}
	
	
	public double getDistance(Position otherPosition) {
		return Math.sqrt(Math.pow((otherPosition.getZ()-this.getZ()),2)+Math.pow(otherPosition.getX()-this.getX(),2));
	}
};
