// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

/************************************************************/
/**
 * 
 */
public interface ProcedureType {
	public void calculateRewards(Rover rover);
};
