// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

/************************************************************/
/**
 * 
 */
public enum ProcedureType {
	procedureA, procedureB;
};
