// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

import project.Environment;
import project.Position;

/************************************************************/
/**
 * 
 */
public class Rover extends RobotAvatar{
	
	private Position position;
	/**
	 * 
	 */
	private int rewardPoints;
	/**
	 * 
	 */
	public Environment rover;
	
	public Rover(Position position, String name) {
		super(position, name);
		this.position = position;
	}

	/**
	 * 
	 * @return 
	 */
	public int getRewardPoints() {
		int i = 0;
		return i;
	}

	/**
	 * 
	 * @param points 
	 */
	public void setRewardPoints(int points) {
	}

	/**
	 * 
	 * @param point 
	 */
	public void moveToPoint(Position pos) {
		this.setDestination(pos);
	}
	
	public Position getPosition() {
		return this.position;
	}
	
};
