// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

import project.Environment;
import project.Position;

/************************************************************/
/**
 * 
 */
public class Rover extends RobotAvatar{
	

	/**
	 * 
	 */
	private int rewardPoints;
	/**
	 * 
	 */
	public Environment inEnvironment;
	
	public Rover(Point position, String name) {
		super(position, name);
	}

	/**
	 * 
	 * @return 
	 */
	public int getRewardPoints() {
		return rewardPoints;
	}

	/**
	 * 
	 * @param points 
	 */
	public void addRewardPoints(int points) {
		rewardPoints += points; 
	}

	/**
	 * 
	 * @param point 
	 */
	public void moveToPoint(Point point) {
	}
};
