// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

import project.Environment;
import project.Position;

/************************************************************/
/**
 * 
 */
public class Rover {
	/**
	 * 
	 */
	private int rewardPoints;
	/**
	 * 
	 */
	public Environment rover;

	/**
	 * 
	 * @return 
	 */
	public int getRewardPoints() {
		int i = 0;
		return i;
	}

	/**
	 * 
	 * @param points 
	 */
	public void setRewardPoints(int points) {
	}

	/**
	 * 
	 * @param point 
	 */
	public void moveToPoint(Point point) {
	}
};
