// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

/************************************************************/
/**
 * 
 */
public enum StrategyType {
	/**
	 * 
	 */
	optimizeLength,
	/**
	 * 
	 */
	optimizeTime;
};
