// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MDSD;

import MDSD.Environment;
import MDSD.Mission;
import MDSD.Point;

/************************************************************/
/**
 * 
 */
public class Strategy {
	/**
	 * 
	 * @param mission 
	 * @param environment 
	 * @return 
	 * @param type 
	 */
	public Point calculateNextPoint(Mission mission, Environment environment, undefined type) {
	}
};
