// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

import project.Rover;

/************************************************************/
/**
 * 
 */
public class User {
	/**
	 * 
	 */
	public Rover[] rover;
};
