// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package area;

import java.util.HashSet;
import java.util.Set;

import project.Mission;
import project.Position;
import project.Rover;
import simbad.sim.EnvironmentDescription;
import simbad.sim.Boundary;

/************************************************************/
/**
 * 
 */
public abstract class Environment extends EnvironmentDescription{

	/**
	 * 
	 */
	protected Set<Position> positions;
	private Set<Area> areas;
	protected Set<Rover> rovers = new HashSet<>();
	protected Mission[] missions = new Mission[4];

	
	public Environment() {
		super();
		areas = new HashSet<>();
	}

	/**
	 * 
	 * @param boundaries 
	 */
	public void setPositions(Set<Position> positions) {
		this.positions=positions;
	}

	/**
	 * 
	 *
	 */
	public Set<Position> getPositions() {
		return positions;
	}
	
	public Set<Area> getAreas(){
		return areas;
	}
	
	public void addArea(Area a) {
		areas.add(a);
	}
	
	public Set<Rover> getRovers() {
		return rovers;
	}
	
	public Mission[] getMissions() {
		return missions;
	}
};
