// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package area;

import java.awt.Color;
import java.util.HashSet;
import java.util.Set;

import project.Mission;
import project.Position;
import project.Rover;
import simbad.sim.EnvironmentDescription;
import simbad.sim.HorizontalBoundary;
import simbad.sim.HorizontalWall;
import simbad.sim.VerticalBoundary;
import simbad.sim.VerticalWall;
import simbad.sim.AbstractWall;
import simbad.sim.Boundary;

/************************************************************/
/**
 * 
 */
public abstract class Environment extends EnvironmentDescription{

	/**
	 * 
	 */
	protected Set<Position> positions;
	private Set<Area> areas;
	private Set<Boundary> boundries;
	private Set<AbstractWall> walls;
	protected Set<Rover> rovers = new HashSet<>();
	protected Mission[] missions = new Mission[4];

	
	public Environment() {
		super();
		boundries = new HashSet<>();
		walls = new HashSet();
		areas = new HashSet<>();
	}

	/**
	 * 
	 * @param boundaries 
	 */
	public void setPositions(Set<Position> positions) {
		this.positions=positions;
	}

	/**
	 * 
	 *
	 */
	public Set<Position> getPositions() {
		return positions;
	}
	
	public Set<Area> getAreas(){
		return areas;
	}
	
	public void addArea(Area a) {
		areas.add(a);
	}
	
	public Set<Rover> getRovers() {
		return rovers;
	}
	
	public Mission[] getMissions() {
		return missions;
	}
	
	public void addBoundry(float p1, float p2, float length, EnvironmentDescription e, Color c, boolean horizontal) {
		if(horizontal) {
			boundries.add(new HorizontalBoundary(p1, p2, length, e, c));
		} else {
			boundries.add(new VerticalBoundary(p1, p2, length, e, c));
		}
	}
	
	public void addWall(float p1, float p2, float length, EnvironmentDescription e, Color c, boolean horizontal) {
		if(horizontal) {
			walls.add(new HorizontalWall(p1, p2, length, e, c));
		} else {
			walls.add(new VerticalWall(p1, p2, length, e, c));
		}
	}
	
	public Set<AbstractWall> getWalls(){
		return walls;
	}
	
	public Set<Boundary> getBoundries(){
		return boundries;
	}
	
};
